server:
    port: 8082
mail:
    host: "smtp.gmail.com"
    port: 587
    username: "#####@gmail.com"
    password: "#####"
    protocol: "smtp"
    auth: true
    starttls-enable: true
    debug: false